version: 2
formats: all

build:
  os: ubuntu-22.04

python:
      version: 3.1
      install:
            - requirements: doc/requirements.txt

sphinx:
      builder: html
      configuration: doc/sphinx/conf.py
