name: Run test suite
on: [push, pull_request]
jobs:
      run-tests-direct:
            name: Run tests on source directory
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v4
              with:
                python-version: '3.10' 
            - run: sudo apt install libblas-dev liblapack-dev
            - run: pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
            - run: pip3 install --user -r requirements.txt
            - run: export OMP_NUM_THREADS=1
            - run: nose2 --output-buffer
      make-test-package:
            name: Test making the package
            runs-on: ubuntu-latest
            steps:
                  - uses: actions/checkout@v2
                    with:
                          submodules: recursive
                  - uses: actions/setup-python@v4
                    with:
                      python-version: '3.10'
                    name: Install Python
                  - name: Build source distribution
                    run: python setup.py sdist
                  - uses: actions/upload-artifact@v2
                    with:
                          path: dist/*.tar.gz
                          name: packages
