name: Run test suite
on: [push, pull_request]
jobs:
      run-tests:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
            - run: sudo apt-get install python3-setuptools python3-pip
            - run: pip3 install --user -r requirements.txt
            - run: nosetests
